/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.EnterpriseAdmins;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sagar
 */

public class PanelTransportationManageUserAccount extends javax.swing.JPanel {
    
    private final Enterprise enterprise;
    private final EcoSystem ecosystem;
    Organization organization;
    private final OrganizationDirectory organizationDirectory;
    /**
     * Creates new form PanelTransportationManagerUserAccount
     */
    public PanelTransportationManageUserAccount(Enterprise enterprise, EcoSystem system, Organization organization, OrganizationDirectory organizationDirectory) {
        initComponents();
        initComponents();
        this.enterprise = enterprise;
        this.ecosystem = system;
        this.organization = organization;
        this.organizationDirectory = organizationDirectory;
        System.out.println("Above populateCmbOrganizationName");
        populateCmbOrganizationName();
        populateTable();
    }
    
    public void populateCmbOrganizationName() 
    {
        System.out.println("Inside populateCmbOrganizationName");
        cmbOrganizationName.removeAllItems();
        System.out.println("getOrganizationList : " + organizationDirectory.getOrganizationList());
        for (Organization org : organizationDirectory.getOrganizationList()) 
        {
            System.out.println("org.getName() : " + org.getName());
            cmbOrganizationName.addItem(org.getName());
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblUserAccount.getModel();

        model.setRowCount(0);

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) 
        {
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) 
            {
                Object row[] = new Object[4];
                row[0] = org.getOrgType();
                row[1] = org.getName();
                row[2] = ua;
                row[3] = ua.getRole();
                ((DefaultTableModel) tblUserAccount.getModel()).addRow(row);
            }
        }
    }

    public void populateCmbEmployee(Organization organization) {
        cmbEmployee.removeAllItems();
        System.out.println("populateCmbEmployee : " + Arrays.toString(organization.getEmployeeDirectory().getEmployeeList().toArray()));
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
            System.out.println("Employee : " + employee);
            cmbEmployee.addItem(employee.toString());
        }
        
//        for (Organization org : organizationDirectory.getOrganizationList()) 
//        {
//            if(org.equals(organization))
//            {
//                for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) 
//                {
//                    System.out.println("Employee : " + employee);
//                    cmbEmployee.addItem(employee.toString());   
//                }
//            }
//        }
    }

    private void populateCmbRole(Organization organization) {
        cmbRole.removeAllItems();
        System.out.println("Inside populateCmbRole");
        for (Role role : organization.getSupportedRole()) 
        {
            cmbRole.addItem(role.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOrganizationName = new javax.swing.JComboBox<>();
        cmbEmployee = new javax.swing.JComboBox<>();
        cmbRole = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        lblOrganizationName = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblOrganizationType = new javax.swing.JLabel();
        btnAddUserAccount = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 238, 234));
        setPreferredSize(new java.awt.Dimension(1140, 800));

        cmbOrganizationName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganizationName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOrganizationNameItemStateChanged(evt);
            }
        });
        cmbOrganizationName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbOrganizationNameFocusLost(evt);
            }
        });
        cmbOrganizationName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbOrganizationNameMousePressed(evt);
            }
        });
        cmbOrganizationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationNameActionPerformed(evt);
            }
        });
        cmbOrganizationName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbOrganizationNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbOrganizationNameKeyTyped(evt);
            }
        });

        cmbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrganizationName.setText("Employee:");
        lblOrganizationName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(167, 196, 188)));

        lblOrganizationType.setText("Organization Type:");
        lblOrganizationType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(167, 196, 188)));

        btnAddUserAccount.setText("Create User Account");
        btnAddUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserAccountActionPerformed(evt);
            }
        });

        lblRole.setText("Role:");
        lblRole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(167, 196, 188)));

        lblUsername.setText("Username:");
        lblUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(167, 196, 188)));

        lblPassword.setText("Password:");
        lblPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(167, 196, 188)));

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Organization Type", "Organization Name", "Username", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblUserAccount);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("MANAGE TRANSPORTATION ENTERPRISE USERS ");
        lblTitle3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcons/TRY2 copy.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcons/TRY2 copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddUserAccount)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbOrganizationName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsername)
                                .addComponent(txtPassword)
                                .addComponent(cmbRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddUserAccount)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserAccountActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        if ("".equals(username) || "".equals(password)|| cmbOrganizationName.getSelectedItem() == null || cmbEmployee.getSelectedItem() == null || cmbRole.getSelectedItem() == null) 
        {
            JOptionPane.showMessageDialog(null, "Please enter all required fields!");
            return;
        }
        if (!ecosystem.validatePasswordFormat(password)) {
            return;
        }
        if (!ecosystem.checkUniqueUsername(username)) {
            return;
        }
        String orgn = null;
        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
        {
            System.out.println("cmbOrganizationName Not null");
            orgn = cmbOrganizationName.getSelectedItem().toString();
            System.out.println("cmbOrganizationName orgn : " + orgn);
        }
            
        
        Organization org = null;
        for(Organization o : organizationDirectory.getOrganizationList())
        {
            if(o.getName().equals(orgn))
            {
            System.out.println("o: " + o);
                org = o;
            }
        }
        
        String emp = cmbEmployee.getSelectedItem().toString();
        Employee employee = null;
//        System.out.println("getEmployeeList" + org.getEmployeeDirectory().getEmployeeList());
        for(Employee e : org.getEmployeeDirectory().getEmployeeList())
        {
            if(e.getName().equals(emp))
                employee = e;
        }
        
        String roleName = cmbRole.getSelectedItem().toString();
        Role role = null;
        for(Role r : org.getSupportedRole())
        {
            if(r.toString().equals(roleName))
                role = r;
        }
        
//        Role role = (Role) cmbRole.getSelectedItem();
        org.getUserAccountDirectory().createUserAccount(username, password, employee, role);
        populateTable();
        txtUsername.setText("");
        txtPassword.setText("");
        JOptionPane.showMessageDialog(null, "User created successfully");
    }//GEN-LAST:event_btnAddUserAccountActionPerformed

    private void cmbOrganizationNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbOrganizationNameKeyPressed
        // TODO add your handling code here:
//        System.out.println("Inside cmbOrganizationNameKeyPressed");
//        String orgn = null;
//        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
//        {
////            System.out.println("cmbOrganizationName Not null");
//            orgn = cmbOrganizationName.getSelectedItem().toString();
////            System.out.println("cmbOrganizationName orgn : " + orgn);
//        }
//            
//        
//        Organization org = null;
//        for(Organization o : organizationDirectory.getOrganizationList())
//        {
//            if(o.getName().equals(orgn))
//            {
////            System.out.println("o: " + o);
//                org = o;
//            }
//        }
//        
//        if (org != null) 
//        {
//            populateCmbEmployee(org);
//            populateCmbRole(org);
//        }
    }//GEN-LAST:event_cmbOrganizationNameKeyPressed

    private void cmbOrganizationNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbOrganizationNameMousePressed
//        String orgn = null;
//        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
//        {
////            System.out.println("cmbOrganizationName Not null");
//            orgn = cmbOrganizationName.getSelectedItem().toString();
////            System.out.println("cmbOrganizationName orgn : " + orgn);
//        }
//            
//        
//        Organization org = null;
//        for(Organization o : organizationDirectory.getOrganizationList())
//        {
//            if(o.getName().equals(orgn))
//            {
////            System.out.println("o: " + o);
//                org = o;
//            }
//        }
//        
//        if (org != null) 
//        {
//            populateCmbEmployee(org);
//            populateCmbRole(org);
//        }
    }//GEN-LAST:event_cmbOrganizationNameMousePressed

    private void cmbOrganizationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationNameActionPerformed
        System.out.println("Inside cmbOrganizationNameActionPerformed");
        String orgn = (String) cmbOrganizationName.getSelectedItem();
//        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
//        {
////            System.out.println("cmbOrganizationName Not null");
//            orgn = cmbOrganizationName.getSelectedItem().toString();
////            System.out.println("cmbOrganizationName orgn : " + orgn);
//        }
            
        
        Organization org = null;
        for(Organization o : organizationDirectory.getOrganizationList())
        {
            if(o.getName().equals(orgn))
            {
            System.out.println("o: " + o);
                org = o;
            }
        }
        
        if (org != null) 
        {
            populateCmbEmployee(org);
            populateCmbRole(org);
        }
    }//GEN-LAST:event_cmbOrganizationNameActionPerformed

    private void cmbOrganizationNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbOrganizationNameFocusLost
//        String orgn = null;
//        cmbOrganizationName.setSelectedItem("Item");
//        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
//        {
////            System.out.println("cmbOrganizationName Not null");
//            orgn = cmbOrganizationName.getSelectedItem().toString();
////            System.out.println("cmbOrganizationName orgn : " + orgn);
//        }
//            
//        
//        Organization org = null;
//        for(Organization o : organizationDirectory.getOrganizationList())
//        {
//            if(o.getName().equals(orgn))
//            {
////            System.out.println("o: " + o);
//                org = o;
//            }
//        }
//        
//        if (org != null) 
//        {
//            populateCmbEmployee(org);
//            populateCmbRole(org);
//        }
    }//GEN-LAST:event_cmbOrganizationNameFocusLost

    private void cmbOrganizationNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOrganizationNameItemStateChanged
        // TODO add your handling code here:
//        System.out.println("Inside cmbOrganizationNameItemStateChanged");
//        String orgn = null;
//        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
//        {
////            System.out.println("cmbOrganizationName Not null");
//            orgn = cmbOrganizationName.getSelectedItem().toString();
////            System.out.println("cmbOrganizationName orgn : " + orgn);
//        }
//            
//        
//        Organization org = null;
//        for(Organization o : organizationDirectory.getOrganizationList())
//        {
//            if(o.getName().equals(orgn))
//            {
////            System.out.println("o: " + o);
//                org = o;
//            }
//        }
//        
//        if (org != null) 
//        {
//            populateCmbEmployee(org);
//            populateCmbRole(org);
//        }
    }//GEN-LAST:event_cmbOrganizationNameItemStateChanged

    private void cmbOrganizationNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbOrganizationNameKeyTyped
        System.out.println("Inside cmbOrganizationNameKeyTyped");
        String orgn = (String) cmbOrganizationName.getSelectedItem();
        if(!cmbOrganizationName.getSelectedItem().toString().equals(null))
        {
//            System.out.println("cmbOrganizationName Not null");
            orgn = cmbOrganizationName.getSelectedItem().toString();
//            System.out.println("cmbOrganizationName orgn : " + orgn);
        }
            
        
        Organization org = null;
        for(Organization o : organizationDirectory.getOrganizationList())
        {
            if(o.getName().equals(orgn))
            {
//            System.out.println("o: " + o);
                org = o;
            }
        }
        
        if (org != null) 
        {
            populateCmbEmployee(org);
            populateCmbRole(org);
        }
    }//GEN-LAST:event_cmbOrganizationNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUserAccount;
    private javax.swing.JComboBox<String> cmbEmployee;
    private javax.swing.JComboBox<String> cmbOrganizationName;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblUserAccount;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
